name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 0.10.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  quill_delta: ^1.0.0
  notus:
    path: ../notus
  meta: ^1.1.0
  quiver_hashcode: ^2.0.0
  flutter_screenutil: ^1.0.2
  image_picker: ^0.6.1
  dio: 3.0.9
  fluttertoast: ^4.0.0
  flutter_luban: 
    path: ./flutter_luban
  path_provider: ^1.6.5

dev_dependencies:
  pedantic: ^1.0.0


# The following section is specific to Flutter.
flutter:
  # To add assets to your application, add an assets section, like this:
  # 导入images下面的所有图片
  assets:
    - images/
